-- Expand seed to ~120 records: ~40 today, ~40 yesterday, ~40 historical.
-- Theme distribution weighted; enterprise concentrated in Auth/Support; sources uneven.
-- Schema unchanged.

DELETE FROM feedback;

-- Today (~40): Auth 12, Support 4, API Timeout 6, Email 3, Docs 3. Four Support rows moved to yesterday so Support Response Delays shows a decrease (yesterday 9, today 4) and remains in top 3. Auth unchanged (trending up).
INSERT INTO feedback (source, sentiment, comment, timestamp) VALUES
('Customer Support Tickets', 'negative', 'Users unable to log in via SSO; timeout after redirect.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-0 minutes')),
('Customer Support Tickets', 'negative', 'SSO login fails after IdP redirect; session not created.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-10 minutes')),
('Email', 'negative', 'Login with Google returns to homepage; still logged out.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-20 minutes')),
('Customer Support Tickets', 'negative', 'Password reset link says expired but was clicked within 10 min.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-30 minutes')),
('Discord', 'negative', 'Auth token invalid after deploy; had to re-login.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-40 minutes')),
('GitHub issues', 'neutral', 'Session drops when switching between orgs.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-50 minutes')),
('Customer Support Tickets', 'negative', 'Enterprise SSO not working for new IdP configuration.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-60 minutes')),
('Discord', 'negative', 'Cannot log in with SAML; redirect loop.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-70 minutes')),
('GitHub issues', 'negative', 'Login fails intermittently; 401 after successful auth.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-80 minutes')),
('Email', 'negative', 'SSO login broken for our domain since last week.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-90 minutes')),
('Customer Support Tickets', 'negative', 'Support ticket open for 48 hours without update.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-100 minutes')),
('Customer Support Tickets', 'negative', 'No response to ticket #8821 for 3 days.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-110 minutes')),
('Discord', 'neutral', 'Support reply took 5 days; issue was urgent.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-120 minutes')),
('GitHub issues', 'negative', 'Slow response time on support requests.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-130 minutes')),
('Customer Support Tickets', 'negative', 'Waiting 72 hours for support reply on billing.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-140 minutes')),
('Discord', 'negative', 'Support delay caused outage to escalate.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-150 minutes')),
('GitHub issues', 'neutral', 'Ticket response time too long for enterprise SLA.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-160 minutes')),
('community forums', 'negative', 'No reply from support in 4 days.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-170 minutes')),
('Customer Support Tickets', 'negative', 'API requests intermittently failing with 504.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-180 minutes')),
('GitHub issues', 'negative', 'Gateway timeout on API during peak.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-190 minutes')),
('Discord', 'negative', 'API timeout errors when fetching large dataset.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-200 minutes')),
('GitHub issues', 'negative', '504 on bulk export API; retries did not help.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-210 minutes')),
('Discord', 'neutral', 'API sometimes times out; no clear pattern.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-220 minutes')),
('X/Twitter', 'negative', 'Getting 504 when calling API from edge.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-230 minutes')),
('Email', 'negative', 'Email verification not being delivered.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-240 minutes')),
('Discord', 'neutral', 'Verification emails not arriving; checked spam.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-250 minutes')),
('GitHub issues', 'negative', 'Notification emails delayed by hours.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-260 minutes')),
('community forums', 'neutral', 'Email delivery inconsistent for alerts.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-270 minutes')),
('GitHub issues', 'neutral', 'Docs unclear about required webhook headers.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-280 minutes')),
('Discord', 'neutral', 'Documentation scattered; hard to find API auth page.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-290 minutes')),
('community forums', 'negative', 'Docs say one thing but API expects another.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-300 minutes')),
('GitHub issues', 'negative', 'Webhook signature validation failing; docs missing example.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-310 minutes')),
('Discord', 'neutral', 'Billing dashboard export missing for custom range.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-320 minutes')),
('GitHub issues', 'neutral', 'DNS propagation timing not documented.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-330 minutes')),
('Customer Support Tickets', 'negative', 'Edge function cold start confusion; no guidance.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-340 minutes')),
('community forums', 'neutral', 'WAF rule preview unclear what will be blocked.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-350 minutes')),
('GitHub issues', 'negative', 'API rate limit message does not specify reset time.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-360 minutes')),
('Discord', 'neutral', 'OAuth redirect URI mismatch in docs.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-370 minutes')),
('X/Twitter', 'negative', 'SSL certificate renewal delay caused downtime.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-380 minutes')),
('GitHub issues', 'neutral', 'Rate limit error message does not specify reset time.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-390 minutes'));

-- Yesterday (~40): Auth 4, Support 9, API Timeout 5, others lower. Four Support rows moved from today so one top-3 theme shows a decrease.
INSERT INTO feedback (source, sentiment, comment, timestamp) VALUES
('Customer Support Tickets', 'negative', 'SSO login failed once today.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-0 minutes')),
('Discord', 'neutral', 'Had to re-authenticate after update.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-15 minutes')),
('GitHub issues', 'negative', 'Login timeout under load.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-30 minutes')),
('Email', 'negative', 'Password reset link expired too quickly.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-45 minutes')),
('Customer Support Tickets', 'negative', 'Support ticket open 24h no reply.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-60 minutes')),
('GitHub issues', 'neutral', 'Support response took 2 days.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-75 minutes')),
('Discord', 'negative', 'Waiting on support for API access.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-90 minutes')),
('Customer Support Tickets', 'negative', 'Slow support response on critical issue.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-105 minutes')),
('community forums', 'neutral', 'Support replied but after 36 hours.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-120 minutes')),
('Customer Support Tickets', 'negative', 'API returned 504 during migration.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-135 minutes')),
('GitHub issues', 'negative', 'Gateway timeout on list endpoint.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-150 minutes')),
('Discord', 'neutral', 'API timeout when uploading large file.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-165 minutes')),
('GitHub issues', 'negative', '504 errors on API this morning.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-180 minutes')),
('X/Twitter', 'negative', 'API failing with timeout repeatedly.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-195 minutes')),
('Email', 'neutral', 'Email notifications delayed yesterday.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-210 minutes')),
('Discord', 'negative', 'Verification email never arrived.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-225 minutes')),
('GitHub issues', 'neutral', 'Docs missing step for webhook setup.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-240 minutes')),
('community forums', 'neutral', 'Documentation could be clearer.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-255 minutes')),
('Customer Support Tickets', 'negative', 'Link in email was invalid.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-270 minutes')),
('GitHub issues', 'negative', 'Validation error on form submit.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-285 minutes')),
('Discord', 'neutral', 'Issue status confusing in dashboard.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-300 minutes')),
('GitHub issues', 'positive', 'Needs info workflow is clearer now.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-315 minutes')),
('Customer Support Tickets', 'neutral', 'Ticket status labels unclear.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-330 minutes')),
('Discord', 'negative', 'Broken link in dashboard.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-345 minutes')),
('GitHub issues', 'neutral', 'Export failed with unclear error.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-360 minutes')),
('community forums', 'neutral', 'Feature request: better error messages.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-375 minutes')),
('Customer Support Tickets', 'negative', 'Dashboard load slow.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-390 minutes')),
('Email', 'neutral', 'Would like filter by date range.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-405 minutes')),
('GitHub issues', 'positive', 'API v2 is much faster.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-420 minutes')),
('Discord', 'neutral', 'Minor UI bug in settings.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-435 minutes')),
('X/Twitter', 'negative', 'Mobile view broken on login page.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-450 minutes')),
('community forums', 'neutral', 'Question about rate limits.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-465 minutes')),
('Customer Support Tickets', 'negative', 'Billing page shows wrong total.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-480 minutes')),
('GitHub issues', 'neutral', 'Cache purge timing unclear.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-495 minutes')),
('Discord', 'positive', 'Good fix on last release.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-510 minutes')),
('Email', 'neutral', 'Support was helpful once they replied.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-525 minutes')),
('GitHub issues', 'negative', 'Need more examples in docs.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-540 minutes')),
('community forums', 'neutral', 'How to debug webhook failures?', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-555 minutes')),
('Customer Support Tickets', 'neutral', 'Request for audit log export.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-570 minutes')),
('X/Twitter', 'negative', 'Login button unresponsive sometimes.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-585 minutes')),
('Discord', 'neutral', 'Feature request: bulk delete.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-1 day', '-600 minutes'));

-- Historical (~40): 2–7 days ago, varied themes and sources.
INSERT INTO feedback (source, sentiment, comment, timestamp) VALUES
('Customer Support Tickets', 'negative', 'SSO config failed to save.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-2 days', '-0 minutes')),
('GitHub issues', 'negative', 'Auth cookie not set on Safari.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-2 days', '-60 minutes')),
('Discord', 'neutral', 'Support took 4 days to respond.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-2 days', '-120 minutes')),
('Email', 'negative', 'No reply to ticket for 5 days.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-2 days', '-180 minutes')),
('GitHub issues', 'negative', 'API 504 during peak usage.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-2 days', '-240 minutes')),
('Customer Support Tickets', 'negative', 'Email verification link expired.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-2 days', '-300 minutes')),
('community forums', 'neutral', 'Docs need update for new API.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-2 days', '-360 minutes')),
('GitHub issues', 'negative', 'Validation error on optional field.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-3 days', '-0 minutes')),
('Discord', 'negative', 'Login redirect loop with SSO.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-3 days', '-90 minutes')),
('Customer Support Tickets', 'negative', 'Enterprise support delay unacceptable.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-3 days', '-180 minutes')),
('GitHub issues', 'neutral', 'Issue status needs info unclear.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-3 days', '-270 minutes')),
('Email', 'negative', 'API timeout on bulk operation.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-3 days', '-360 minutes')),
('X/Twitter', 'negative', 'Broken link in status page.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-3 days', '-450 minutes')),
('Customer Support Tickets', 'neutral', 'Documentation out of date.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-3 days', '-540 minutes')),
('Discord', 'negative', 'Session expired too quickly.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-4 days', '-0 minutes')),
('GitHub issues', 'negative', 'Support ticket still open after 1 week.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-4 days', '-120 minutes')),
('Customer Support Tickets', 'negative', '504 when calling API from worker.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-4 days', '-240 minutes')),
('community forums', 'neutral', 'Email delivery delayed.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-4 days', '-360 minutes')),
('GitHub issues', 'negative', 'Docs wrong about rate limit.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-4 days', '-480 minutes')),
('Email', 'negative', 'Login failed with MFA enabled.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-5 days', '-0 minutes')),
('Customer Support Tickets', 'negative', 'No response from support in 6 days.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-5 days', '-100 minutes')),
('Discord', 'neutral', 'API timeout on weekend.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-5 days', '-200 minutes')),
('GitHub issues', 'negative', 'Verification email not received.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-5 days', '-300 minutes')),
('X/Twitter', 'negative', 'Error message not helpful.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-5 days', '-400 minutes')),
('Customer Support Tickets', 'neutral', 'Status page unclear during incident.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-5 days', '-500 minutes')),
('GitHub issues', 'negative', 'OAuth redirect mismatch.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-6 days', '-0 minutes')),
('Discord', 'neutral', 'Cold start latency high.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-6 days', '-90 minutes')),
('Email', 'negative', 'Billing export missing columns.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-6 days', '-180 minutes')),
('community forums', 'neutral', 'WAF preview unclear.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-6 days', '-270 minutes')),
('Customer Support Tickets', 'negative', 'Rate limit message vague.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-6 days', '-360 minutes')),
('GitHub issues', 'positive', 'Support resolved issue quickly.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-6 days', '-450 minutes')),
('Discord', 'negative', 'SSL renewal took too long.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-7 days', '-0 minutes')),
('Customer Support Tickets', 'negative', 'API 504 under load.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-7 days', '-60 minutes')),
('GitHub issues', 'neutral', 'Docs for webhook validation missing.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-7 days', '-120 minutes')),
('Email', 'negative', 'Login broken after IdP change.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-7 days', '-180 minutes')),
('X/Twitter', 'neutral', 'DNS propagation not documented.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-7 days', '-240 minutes')),
('community forums', 'negative', 'Dashboard export failed.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-7 days', '-300 minutes')),
('Customer Support Tickets', 'neutral', 'Need better API error codes.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-7 days', '-360 minutes')),
('Discord', 'negative', 'Ticket status confusing.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-7 days', '-420 minutes')),
('GitHub issues', 'negative', 'Email not delivered for 2 days.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-7 days', '-480 minutes')),
('Customer Support Tickets', 'negative', 'Support delay caused escalation.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-7 days', '-540 minutes')),
('Email', 'neutral', 'API timeout error message unclear.', strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-7 days', '-600 minutes'));
